[package]
name = "tip"
version = "2.0.0"
edition = "2021"
authors = ["Whiskerz"]
description = "A tool for managing target IP addresses"

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
dirs = "5.0.0"
regex = "1.8.1"
colored = "2"
